### ISSUE TITLE
Freeze on Delete system on SXOS

### ISSUE THREAD

**Issue by rashevskyv** [StarDustCFW/Haku33#2]
OS 8.1.0 
SXOS 2.9.2

Just freezing on Deletу system

After hard reset with power button console goes to initialization, but updates for all games are existing on the HOME screen

UPD. I tried to repeat an error, but second time all was fine

**Comment by rashevskyv** [comment]
Aso it would be great before turning off console after successed cleaning provide information about console's power off and information about autorcm. When console just powered off without any warnings - it is totaly confusing

**Comment by Kronos2308** [comment]
Haku33 only. Lean the nand don't deactivate autoRCM
The led of the joycon 
Y the led turn on is because all is ok 

In the last version

You get a warning of all complete


Read the info on screen if just freeze the console deactivate airplane mode , and any service 

Is tested on Atmophere and sxos
